qha:
  input: input01
  settings:
    T_MIN: 0
    NT: 21
    DT: 100
    P_MIN: -1
    DELTA_P: 1
    NTV: 17
    p_min_modifier: 0
    order: 3
    static_only: False
    DT_SAMPLE: 300
    DELTA_P_SAMPLE: 5
    volume_ratio: 1.2
  frequency: hbar
elast:
  input: elast.dat
settings:
  mode_gamma:
    interpolator: spline
    order: 4
  cij_keys: [11, 22, 33, 12, 13, 23, 44, 55, 66]
  disable_phonon_contribution: False
  output:
    pressure_base:
      - c11s
      - c22s
      - c33s

    volume_base:
      - c11s
      - c22s
      - c33s